name: Python Test Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -r requirements-dev.txt
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest --cov=./
      - name: Upload coverage data
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: .coverage
